using System;
using System.Text;
using RepoMind.Domain.Models;

namespace RepoMind.Application.Services;

public class HandbookExporter
{
    public static ArchitectureHandbook GenerateHandbook(AnalysisResult analysis)
    {
        var handbook = new ArchitectureHandbook
        {
            RepositoryName = analysis.Repository.Name,
            GeneratedAt = DateTime.UtcNow
        };

        var sb = new StringBuilder();
        sb.AppendLine($"# System Architecture Specification Handbook: {analysis.Repository.Name}");
        sb.AppendLine($"*Generated by RepoMind Knowledge Platform on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC*");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();

        sb.AppendLine("## 1. Executive Technical Summary");
        sb.AppendLine($"- **Repository Name**: `{analysis.Repository.Name}`");
        sb.AppendLine($"- **Source**: `{(analysis.Repository.Source == RepositorySource.Local ? "Local Directory" : "GitHub Repository")}`");
        sb.AppendLine($"- **Branch**: `{analysis.Repository.Branch ?? "main"}`");
        sb.AppendLine($"- **Commit SHA**: `{analysis.Repository.CommitHash ?? "Latest"}`");
        sb.AppendLine($"- **AST Entities Extracted**: `{analysis.Entities.Count}`");
        sb.AppendLine($"- **REST APIs Exposed**: `{analysis.Apis.Count}`");
        sb.AppendLine($"- **Database Operations**: `{analysis.Databases.Count}`");
        sb.AppendLine($"- **Functional Flows**: `{analysis.Flows.Count}`");
        sb.AppendLine();

        sb.AppendLine("## 2. REST API Endpoints Specification");
        sb.AppendLine("| HTTP Method | Route | Controller | Action Method | File Path |");
        sb.AppendLine("| :--- | :--- | :--- | :--- | :--- |");
        foreach (var api in analysis.Apis)
        {
            sb.AppendLine($"| `{api.HttpMethod}` | `{api.Route}` | `{api.ControllerName}` | `{api.ActionName}` | `{api.FilePath}:{api.LineNumber}` |");
        }
        sb.AppendLine();

        sb.AppendLine("## 3. Database Schema & Persistence Operations");
        sb.AppendLine("| Table Name | Operation | ORM Provider | Source Component | File Path |");
        sb.AppendLine("| :--- | :--- | :--- | :--- | :--- |");
        foreach (var db in analysis.Databases)
        {
            sb.AppendLine($"| `{db.TableName}` | `{db.Operation}` | `{db.OrmProvider}` | `{db.SourceEntity}` | `{db.FilePath}:{db.LineNumber}` |");
        }
        sb.AppendLine();

        sb.AppendLine("## 4. End-to-End Functional Flows");
        foreach (var flow in analysis.Flows)
        {
            sb.AppendLine($"### Flow: {flow.Title}");
            sb.AppendLine($"**Trigger Route**: `{flow.TriggerApi}`");
            sb.AppendLine();
            sb.AppendLine("```mermaid");
            sb.AppendLine(flow.MermaidMarkup);
            sb.AppendLine("```");
            sb.AppendLine();
        }

        handbook.MarkdownContent = sb.ToString();
        return handbook;
    }
}
