using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using CodeAtlas.Domain.Models;

namespace CodeAtlas.Application.Services
{
    public class GeminiAiService
    {
        private static readonly HttpClient HttpClient = new HttpClient();

        public async Task<string> AskCodebaseAsync(
            AnalysisResult analysis,
            string userPrompt,
            string userApiKey = null)
        {
            var apiKey = !string.IsNullOrWhiteSpace(userApiKey)
                ? userApiKey
                : Environment.GetEnvironmentVariable("GEMINI_API_KEY");

            if (string.IsNullOrWhiteSpace(apiKey))
            {
                throw new InvalidOperationException(
                    "No Gemini API key provided. Please enter your free Gemini API Key in CodeAtlas AI Assistant settings or configure GEMINI_API_KEY on the server.");
            }

            var contextPrompt = BuildCodebaseContextPrompt(analysis, userPrompt);
            var endpointUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={apiKey.Trim()}";

            var requestBody = new
            {
                contents = new[]
                {
                    new
                    {
                        role = "user",
                        parts = new[]
                        {
                            new { text = contextPrompt }
                        }
                    }
                },
                generationConfig = new
                {
                    temperature = 0.2,
                    maxOutputTokens = 2048
                }
            };

            var jsonContent = new StringContent(
                JsonSerializer.Serialize(requestBody),
                Encoding.UTF8,
                "application/json");

            var response = await HttpClient.PostAsync(endpointUrl, jsonContent);
            var responseString = await response.Content.ReadAsStringAsync();

            if (!response.IsSuccessStatusCode)
            {
                if ((int)response.StatusCode == 429)
                {
                    throw new InvalidOperationException(
                        "Google Gemini API rate limit reached (15 requests/min). Please wait a few seconds or enter your personal free Gemini API Key in settings.");
                }

                throw new HttpRequestException($"Gemini API error ({response.StatusCode}): {responseString}");
            }

            using var doc = JsonDocument.Parse(responseString);
            var root = doc.RootElement;

            if (root.TryGetProperty("candidates", out var candidates) &&
                candidates.ValueKind == JsonValueKind.Array &&
                candidates.GetArrayLength() > 0)
            {
                var candidate = candidates[0];
                if (candidate.TryGetProperty("content", out var content) &&
                    content.TryGetProperty("parts", out var parts) &&
                    parts.ValueKind == JsonValueKind.Array &&
                    parts.GetArrayLength() > 0)
                {
                    var text = parts[0].GetProperty("text").GetString();
                    return text ?? "No response generated by Gemini AI.";
                }
            }

            return "Unable to parse Gemini AI response.";
        }

        private string BuildCodebaseContextPrompt(
            AnalysisResult analysis,
            string userPrompt)
        {
            var sb = new StringBuilder();
            sb.AppendLine("You are CodeAtlas AI — an elite Senior Principal Software Architect and Codebase Knowledge Graph AI Assistant.");
            sb.AppendLine("You have full access to the AST analysis, REST endpoints, Database Schemas, Messaging Events, and Functional Flows of this repository.");
            sb.AppendLine();
            sb.AppendLine("=== REPOSITORY METADATA ===");
            sb.AppendLine($"Repository Name: {analysis?.Repository?.Name ?? "CodeAtlas Project"}");
            sb.AppendLine($"Branch: {analysis?.Repository?.Branch ?? "main"}");
            sb.AppendLine($"Root Path: {analysis?.Repository?.RootPath ?? "/app"}");
            sb.AppendLine($"Commit SHA: {analysis?.Repository?.CommitHash ?? "HEAD"}");
            sb.AppendLine();

            if (analysis?.Apis != null && analysis.Apis.Count > 0)
            {
                sb.AppendLine("=== REST ENDPOINTS ===");
                foreach (var api in analysis.Apis.Take(15))
                {
                    sb.AppendLine($"- [{api.HttpMethod}] {api.Route} -> Controller: {api.ControllerName}, Method: {api.ActionName} ({api.FilePath}:{api.LineNumber})");
                }
                sb.AppendLine();
            }

            if (analysis?.Databases != null && analysis.Databases.Count > 0)
            {
                sb.AppendLine("=== DATABASE SCHEMAS & TABLES ===");
                foreach (var db in analysis.Databases.Take(10))
                {
                    sb.AppendLine($"- Table: {db.TableName} (Op: {db.Operation}, Provider: {db.OrmProvider}) -> Source: {db.SourceEntity} ({db.FilePath}:{db.LineNumber})");
                }
                sb.AppendLine();
            }

            if (analysis?.Flows != null && analysis.Flows.Count > 0)
            {
                sb.AppendLine("=== FUNCTIONAL EXECUTION FLOWS ===");
                foreach (var flow in analysis.Flows.Take(5))
                {
                    sb.AppendLine($"- Flow: '{flow.Title}' (Trigger: {flow.TriggerApi})");
                    sb.AppendLine($"  Description: {flow.Description}");
                    sb.AppendLine($"  Steps: {string.Join(" -> ", flow.Steps.Select(s => $"{s.NodeName} ({s.NodeType})"))}");
                }
                sb.AppendLine();
            }

            if (analysis?.Entities != null && analysis.Entities.Count > 0)
            {
                sb.AppendLine("=== CORE AST ENTITIES & CLASSES ===");
                foreach (var entity in analysis.Entities.Take(25))
                {
                    sb.AppendLine($"- {entity.Type} {entity.Name} (FullName: {entity.FullName}, File: {entity.FilePath}:{entity.StartLine})");
                }
                sb.AppendLine();
            }

            sb.AppendLine("=== USER QUESTION ===");
            sb.AppendLine(userPrompt);
            sb.AppendLine();
            sb.AppendLine("INSTRUCTIONS FOR CODEATLAS AI:");
            sb.AppendLine("1. Answer the user question concisely, accurately, and professionally using the codebase context provided above.");
            sb.AppendLine("2. When mentioning files, classes, or APIs, format them clearly in Markdown code blocks (e.g. `OrderService.cs`).");
            sb.AppendLine("3. If asking for code generation or test cases, provide complete, production-ready code snippets with docstrings.");

            return sb.ToString();
        }
    }
}
